#!/usr/bin/env bash
qemu-system-aarch64 \
    -machine virt,virtualization=on \
    -cpu cortex-a53 \
    -nographic \
    -serial mon:stdio \
    -device loader,file=tmp_build/loader.img,addr=0x70000000,cpu-num=0 \
    -m size=2G
